### ISSUE TITLE
numpy is taking a long time to install in older devices

### ISSUE THREAD

**Issue by celifani** [Crowd-Management-Japan/blescan#11]
numpy needs almost 30 minutes to be installed in Pi3 devices and probably even longer in PiZero devices. The only calculations that are performed using nunpy is average and std. These calculations can be done with simple formulas without using numpy. In light of this is probably better to remove numpy from the requirements list and use simple equations when computing average and standard deviation.

**Comment by tobiasarens** [comment]
Fixed on the bugfix_tokyodome branch. Will soon be merged to master
I heavily trimmed the requirements file and swapped numpy with the statistics package.
