### ISSUE TITLE
LEDs improvement

### ISSUE THREAD

**Issue by celifani** [Crowd-Management-Japan/blescan#12]
LEDs are an important features to understand whether the program is running in conditions where there is no access to the network and is not possible to physically connect to each device. I would suggest that one LED could be used to indicate the status of the program, for example blinking when is running and constantly off when dead. The other LED could be used for communication. For example a blinking light could be used to indicate that communication is working and no light to indicate that there is no communication. In this way it would be possible to understand whether the program is running but saving the data locally or whether communication with the backend/coordination has been established.
LEDs should work for all users, but if sudo is needed we could have this "special" feature only for su users, which is probably most of the people using this program.

_Originally posted by @celifani in https://github.com/Crowd-Management-Japan/blescan/issues/2#issuecomment-1920567055_

**Comment by celifani** [comment]
LED for normal operation should be changed because it looks too similar to missing internet connection. I suggest that the "no internet connection" blinking could be kept but a faster heartbeat may help. For example, 3 short flashing blinks followed by a longer pause.

**Comment by tobiasarens** [comment]
This was fixed by changing threads to processes, as threads seem to not have proper timing.
When using processes the blinking behaviour can be observed correctly.
