### ISSUE TITLE
Delete previous existing folder before installation?

### ISSUE THREAD

**Issue by celifani** [Crowd-Management-Japan/blescan#17]
An already existing folder for the program can cause problems during installation in relation to git up synchronization. Would it be appropriate to remove the folder before installing the program? Not an elegant solution but could prevent unwanted errors.

**Comment by tobiasarens** [comment]
The folder should not be deleted, but a check whether it is already existing should be added.
If it is the case the installation ends with an error and the user can manually delete the folder

**Comment by tobiasarens** [comment]
done.
This is added to the backend script
