### ISSUE TITLE
LED Status

### ISSUE THREAD

**Issue by tobiasarens** [Crowd-Management-Japan/blescan#2]
Use the LEDs on the raspberry board for outside communication.

A basic implementation exists, but it should be enhanced to show data sent/received and errors.

**Comment by celifani** [comment]
LEDs are an important features to understand whether the program is running in conditions where there is no access to the network and is not possible to physically connect to each device. I would suggest that one LED could be used to indicate the status of the program, for example blinking when is running and constantly off when dead. The other LED could be used for communication. For example a blinking light could be used to indicate that communication is working and no light to indicate that there is no communication. In this way it would be possible to understand whether the program is running but saving the data locally or whether communication with the backend/coordination has been established.
LEDs should work for all users, but if sudo is needed we could have this "special" feature only for su users, which is probably most of the people using this program.
